# src/hal/sdr.py
# TALOS SDR Hardware Abstraction Layer (HAL)
#
# Production-minded goals (soft real-time safe):
# - FFT-safe framing: "all-or-nothing" IQ frames (FULL frame or EMPTY).
# - CPU safety: never spin at 100% CPU on fast-fail loops (micro-sleep).
# - Hardware optional: SoapySDR optional; emulator fallback for CI/dev.
# - Production control: allow_emulation flag (config.allow_emulation if present).
# - Robust readStream return handling: object/int/tuple -> normalized.
# - Observability without log spam: throttled logging + local counters.
# - Spawn/pickle friendly: avoid non-picklable objects in __init__ (lazy logger; no device/stream in __init__).
#
# Notes:
# - Returned IQ buffer may be reused between calls (performance). Do NOT store it long-term or put it into queues.
# - If you need long-lived samples, explicitly copy downstream: samples_copy = samples.copy()

from __future__ import annotations

from src.sim.rf_environment import RFEnvironmentSimulator


class VirtualSDRDevice:
    """
    Virtual SDR device backed by the RFEnvironmentSimulator.

    This behaves like a minimal SDR hardware interface that returns
    IQ frames generated by the simulated RF environment.

    The interface intentionally mirrors the small subset of behaviour
    the HAL needs: "read_samples" returning complex64 IQ buffers.
    """

    def __init__(self) -> None:
        self._env = RFEnvironmentSimulator()

    def read_samples(
        self,
        num_samples: int,
        sample_rate_hz: float,
        center_freq_hz: float,
    ) -> NDArray[np.complex64]:
        """
        Generate a synthetic IQ frame from the RF simulator.
        """
        return self._env.next_iq_frame(
            num_samples=num_samples,
            sample_rate_hz=sample_rate_hz,
            center_freq_hz=center_freq_hz,
        )

import logging
import time
from typing import Any, Final, Optional, Literal

import numpy as np
from numpy.typing import NDArray

from src.core.types import HalState, SdrConfig

# =============================================================================
# Optional SoapySDR import (runtime-first)
#
# IMPORTANT (Pylance noise avoidance):
# - Define SOAPY_* symbols in *both* branches to avoid NameError.
# - Do NOT reassign uppercase flags across branches -> no "constant redefinition".
# =============================================================================
try:
    import SoapySDR  # type: ignore
    from SoapySDR import SOAPY_SDR_CF32, SOAPY_SDR_RX  # type: ignore
except ImportError:
    SoapySDR = None  # type: ignore[assignment]
    SOAPY_SDR_CF32 = None  # type: ignore[assignment]
    SOAPY_SDR_RX = None  # type: ignore[assignment]

_HAS_SOAPY: Final[bool] = SoapySDR is not None


class SdrDriver:
    """
    TALOS SDR HAL Driver (SoapySDR + Emulator fallback)

    Contract (FFT-safe, critical for CFAR):
      read_samples(N) returns:
        - full frame: NDArray[np.complex64] with len == N
        - empty frame: NDArray[np.complex64] with len == 0 ("Graceful Skip")
      Never return partial / zero-padded frames into FFT (prevents false positives).

    CPU safety:
      When device/stream fails fast (readStream returns immediately), micro-sleep to
      avoid hot-loop burn (caller loop_sleep_s can be 0.0 in DSP worker).

    Emulator:
      Noise + periodic tone burst, with pacing sleep approximating real-time.

    Pickle/spawn safety:
      Keep __init__ minimal. Initialize device/stream only in connect().
      Logger is lazy (property) to avoid pickle quirks on spawn platforms.
    """

    # --- Busy-wait protection (DSP loops can be hot) ---
    _SLEEP_NOT_SCANNING_S: Final[float] = 0.05
    _SLEEP_FASTFAIL_S: Final[float] = 0.002  # 2ms: cheap CPU protection

    # --- Explicit Soapy read timeout (defensive: prevent rare driver hangs) ---
    _READ_TIMEOUT_US: Final[int] = 100_000  # 100 ms

    # --- Connection retry throttle (avoid connect spam loops) ---
    _CONNECT_RETRY_MIN_INTERVAL_S: Final[float] = 2.0

    # --- Log throttling (avoid spam in hot path) ---
    _LOG_PARTIAL_EVERY_N: Final[int] = 200
    _LOG_FASTFAIL_EVERY_N: Final[int] = 200
    _LOG_CONNECT_FAIL_EVERY_N: Final[int] = 10

    def __init__(self, config: SdrConfig):
        self.config = config
        self._virtual_sdr: VirtualSDRDevice | None = None
        # Soapy objects frequently lack type stubs; Any is pragmatic.
        self._sdr: Optional[Any] = None
        self._stream: Optional[Any] = None

        # Emulator policy: allow disabling fallback in production (if present in SdrConfig).
        # Default True for dev/CI friendliness.
        self._allow_emulation: bool = bool(getattr(config, "allow_emulation", True))

        # Backend selection flags:
        # - _is_emulated: current mode used by read_samples()
        # - _force_emulated: sticky flag set only when Soapy is absent at import time (or explicitly forced)
        self._force_emulated: bool = (not _HAS_SOAPY) and self._allow_emulation
        self._is_emulated: bool = self._force_emulated

        self.state: HalState = HalState.DISCONNECTED

        # Local per-process counters (debug/metrics; not cross-process aggregated)
        self._partial_reads: int = 0
        self._fastfail_reads: int = 0
        self._partial_drops: int = 0
        self._connect_failures: int = 0

        # Cached empty array for "Graceful Skip" (avoid allocations in hot path)
        self._empty_buf: NDArray[np.complex64] = np.empty(0, dtype=np.complex64)

        # Reusable frame buffer to avoid per-iteration allocations.
        # CONTRACT: returned buffer is owned by SdrDriver and will be overwritten
        # by the next read_samples() call. Downstream must consume immediately.
        self._buf: Optional[NDArray[np.complex64]] = None

        # Connection throttling
        self._last_connect_attempt_ts: float = 0.0

    # -------------------------------------------------------------------------
    # Logging (spawn/pickle safe)
    # -------------------------------------------------------------------------

    @property
    def logger(self) -> logging.Logger:
        # Lazy init ensures logger is constructed in the correct process context
        return logging.getLogger("talos.hal.sdr")

    # -------------------------------------------------------------------------
    # Public API
    # -------------------------------------------------------------------------

    def connect(self) -> None:
        """
        Connect to SDR via SoapySDR if available; otherwise fall back to emulator
        (if allow_emulation=True) or remain DISCONNECTED.

        Production guidance:
          - Set config.allow_emulation=False to avoid silent emulator fallback.
          - Caller can decide whether to alert/restart if driver stays DISCONNECTED.
        """
        now = time.monotonic()
        if (now - self._last_connect_attempt_ts) < self._CONNECT_RETRY_MIN_INTERVAL_S:
            return
        self._last_connect_attempt_ts = now

        # If we already have a live instance/stream, close before reconnect.
        if self._sdr is not None or self._stream is not None:
            self.close()

        self.logger.info(
            "Connecting to SDR... (Target: %.2f MHz, SR: %.2f MS/s, Gain: %.1f dB, allow_emulation=%s)",
            float(self.config.center_freq_hz) / 1e6,
            float(self.config.sample_rate_hz) / 1e6,
            float(self.config.gain_db),
            self._allow_emulation,
        )

        # Hard emulator decision (Soapy absent at import time + emulation allowed).
        if self._force_emulated:
            self._setup_emulator(reason="SoapySDR not available at import time")
            return

        # If Soapy is missing and emulation is disallowed -> remain disconnected.
        if SoapySDR is None or SOAPY_SDR_RX is None or SOAPY_SDR_CF32 is None:
            self._fallback_or_fail("SoapySDR/SOAPY_* not available at runtime")
            return

        try:
            # Enumerate devices. Soapy returns list of dict-like descriptors.
            results: Any = SoapySDR.Device.enumerate()  # type: ignore[attr-defined]
            if not results:
                self._fallback_or_fail("No SDR devices found")
                return

            args: Any = results[0] # type: ignore[attr-defined]
            self._sdr = SoapySDR.Device(args)  # type: ignore[attr-defined]
            if self._sdr is None:  # type: ignore[attr-defined]
                raise RuntimeError("Failed to create SoapySDR device instance")

            # Local Any alias (reduce static analyzer noise).
            sdr: Any = self._sdr  # type: ignore[attr-defined]

            # Configure RX channel 0
            sdr.setSampleRate(SOAPY_SDR_RX, 0, self.config.sample_rate_hz)  # type: ignore[arg-type]
            sdr.setFrequency(SOAPY_SDR_RX, 0, self.config.center_freq_hz)  # type: ignore[arg-type]
            sdr.setGain(SOAPY_SDR_RX, 0, self.config.gain_db)  # type: ignore[arg-type]

            # Setup and activate stream
            self._stream = sdr.setupStream(SOAPY_SDR_RX, SOAPY_SDR_CF32)  # type: ignore[arg-type]
            stream: Any = self._stream  # type: ignore[attr-defined]
            sdr.activateStream(stream)  # type: ignore[attr-defined]

            self._is_emulated = False
            self.state = HalState.SCANNING

            # Hardware key is helpful but must not break startup.
            try:
                hw = str(sdr.getHardwareKey())  # type: ignore[attr-defined]
            except Exception:
                hw = "unknown"

            self.logger.info("SDR Connected: %s", hw)

        except Exception as e:
            self._fallback_or_fail(f"SDR connect error: {e}")

    def read_samples(self, num_samples: int) -> NDArray[np.complex64]:
        """
        Read one *full* IQ frame.

        Contract (All-or-Nothing):
          - Return full frame (len == num_samples) OR empty frame (len == 0).
          - Empty frame means "Graceful Skip" (caller should skip this iteration).

        CPU safety:
          - Micro-sleep on fast-fail to avoid 100% CPU busy loop.

        Performance:
          - Reuses an internal buffer to avoid per-iteration allocations.
          - Returned buffer is overwritten on next call; downstream must consume immediately.
        """
        if self.state != HalState.SCANNING:
            time.sleep(self._SLEEP_NOT_SCANNING_S)
            return self._empty()

        if self._is_emulated:
            return self._generate_fake_samples(num_samples)

        if not self._sdr or not self._stream:
            self._fastfail("SDR not initialized (sdr/stream is None)", level="warning")
            return self._empty()

        # Ensure reusable buffer is allocated for the requested frame size.
        if self._buf is None or self._buf.size != num_samples:
            self._buf = np.empty(num_samples, dtype=np.complex64)

        # Local Any aliases.
        sdr: Any = self._sdr
        stream: Any = self._stream

        # If we use "write-protect in debug" guardrails, restore writeable before filling.
        if __debug__:
            try:
                self._buf.flags.writeable = True
            except Exception:
                pass

        try:
            # Explicit timeoutUs: protect against rare driver hangs.
            # Not all Soapy builds accept timeoutUs kwarg -> fallback to positional call.
            try:
                sr = sdr.readStream(stream, [self._buf], num_samples, timeoutUs=self._READ_TIMEOUT_US)
            except TypeError:
                sr = sdr.readStream(stream, [self._buf], num_samples)

            ret = self._extract_read_count(sr)

            if ret < 0:
                self._fastfail(f"Stream read error code: {ret}", level="error")
                return self._empty()

            # STRICT: discard partial frames (prevents FFT discontinuity artifacts)
            if ret != num_samples:
                self._partial_reads += 1
                self._partial_drops += 1

                if self._partial_reads % self._LOG_PARTIAL_EVERY_N == 1:
                    self.logger.warning(
                        "Partial read discarded (all-or-nothing). Got=%d Expected=%d PartialCount=%d Drops=%d",
                        ret,
                        num_samples,
                        self._partial_reads,
                        self._partial_drops,
                    )

                time.sleep(self._SLEEP_FASTFAIL_S)
                return self._empty()

            # Debug guardrail: discourage accidental mutation / reuse across iterations.
            if __debug__:
                try:
                    self._buf.flags.writeable = False
                except Exception:
                    pass

            return self._buf

        except Exception as e:
            self._fastfail(f"Exception during readStream: {e}", level="error")
            return self._empty()

    def close(self) -> None:
        """
        Close stream/device safely. Must not throw in teardown.
        Safe to call multiple times.
        """
        if self._sdr and self._stream:
            try:
                sdr: Any = self._sdr
                stream: Any = self._stream
                sdr.deactivateStream(stream)
                sdr.closeStream(stream)
            except Exception as e:
                self.logger.error("Error closing stream: %s", e)

        self._sdr = None
        self._stream = None
        self._is_emulated = self._force_emulated 
        self.state = HalState.DISCONNECTED
        self.logger.debug("SDR Closed.")

    def stats(self) -> dict[str, int]:
        """
        Cheap in-process stats snapshot for debugging/metrics.
        (Not aggregated across processes.)
        """
        return {
            "partial_reads": self._partial_reads,
            "fastfail_reads": self._fastfail_reads,
            "partial_drops": self._partial_drops,
            "connect_failures": self._connect_failures,
        }

    # -------------------------------------------------------------------------
    # Internals
    # -------------------------------------------------------------------------

    def _setup_emulator(self, reason: str) -> None:
        """
        Switch to emulator mode (keeps pipeline operational without hardware).
        Uses a virtual RF environment rather than a single toy tone.
        """
        self._is_emulated = True
        self._virtual_sdr = VirtualSDRDevice()
        self.state = HalState.SCANNING
        self.logger.warning(">>> RUNNING IN EMULATION MODE <<< (%s)", reason)
        
    def _fallback_or_fail(self, reason: str) -> None:
        """
        Decide whether to fall back to emulator or fail hard.

        If allow_emulation=False:
          - remain DISCONNECTED
          - caller will observe empty reads (not scanning) and can decide what to do.
        """
        self._connect_failures += 1

        if self._allow_emulation:
            if self._connect_failures % self._LOG_CONNECT_FAIL_EVERY_N == 1:
                self.logger.error("%s. Switching to EMULATOR. (failures=%d)", reason, self._connect_failures)

            # IMPORTANT: connect failures should not permanently lock us into emulator.
            self._setup_emulator(reason=reason)
            return

        self.logger.critical("%s. Emulator fallback DISABLED. Staying DISCONNECTED.", reason)
        self._is_emulated = False
        self.state = HalState.DISCONNECTED
        time.sleep(self._SLEEP_NOT_SCANNING_S)

    def _generate_fake_samples(self, n: int) -> NDArray[np.complex64]:
        """
        Emulator behaves like real-time:
        - sleeps for frame duration
        - returns IQ from the virtual RF environment
        """
        time.sleep(n / float(self.config.sample_rate_hz))

        if self._virtual_sdr is None:
            self._virtual_sdr = VirtualSDRDevice()

        return self._virtual_sdr.read_samples(
            num_samples=n,
            sample_rate_hz=float(self.config.sample_rate_hz),
            center_freq_hz=float(self.config.center_freq_hz),
        )
    def _empty(self) -> NDArray[np.complex64]:
        """
        Cached empty frame for Graceful Skip.
        """
        return self._empty_buf

    def _fastfail(self, reason: str, *, level: Literal["warning", "error"]) -> None:
        """
        Fast-fail handler for errors that return immediately.

        Prevents busy-wait CPU burn when caller loop_sleep_s == 0.0.
        Logging is throttled to avoid spamming.
        """
        self._fastfail_reads += 1
        if self._fastfail_reads % self._LOG_FASTFAIL_EVERY_N == 1:
            msg = "Fast-fail read (graceful skip). Reason=%s FastFailCount=%d"
            if level == "error":
                self.logger.error(msg, reason, self._fastfail_reads)
            else:
                self.logger.warning(msg, reason, self._fastfail_reads)

        time.sleep(self._SLEEP_FASTFAIL_S)

    @staticmethod
    def _extract_read_count(sr: Any) -> int:
        """
        Normalize SoapySDR readStream return types.

        Common patterns:
          - object with attribute `.ret`
          - integer
          - tuple like (ret, flags, timeNs) or similar
          - numpy scalar as first tuple element

        Returns:
          - >=0: number of samples
          - <0 : error code (or sentinel -999999 if unknown)
        """
        if isinstance(sr, int):
            return sr

        if isinstance(sr, tuple) and sr:
            head: Any = sr[0]  # type: ignore[attr-defined]
            try:
                return int(head)  # type: ignore[attr-defined]
            except Exception:
                return -999999

        try:
            ret_any: Any = getattr(sr, "ret") # type: ignore[attr-defined]
            return int(ret_any)
        except Exception:
            return -999999